import turtle
import os
cr = turtle.Turtle()
screen = turtle.Screen()
screen.bgcolor("grey")

cr.penup()
cr.hideturtle()
cr.speed(0)
cr.goto(-250,200)
cr.write("Developer", "center", font=("Arial", 20, "normal"))
cr.goto(-250,170)
cr.color("light grey")
cr.write("Nico", "center", font=("Arial", 20, "normal"))
cr.goto(-250,140)
cr.color("black")
cr.write("Lead Art Designer", "center", font=("Arial", 20, "normal"))
cr.goto(-250,110)
cr.color("light grey")
cr.write("Beckett", "center", font=("Arial", 20, "normal"))
cr.goto(-250,80)
cr.color("black")
cr.write("Thanks To:", "center", font=("Arial", 20, "normal"))
cr.goto(-250,50)
cr.color("light grey")
cr.write("Elijah - Emotional support", "center", font=("Arial", 20, "normal"))
cr.goto(-250,20)
cr.write("Christopher - Pushing me to not procrastinate", "center", font=("Arial", 20, "normal"))
cr.goto(-250, -10)
cr.write("Everyone on the Culinary Share Team - Testing", "center", font=("Arial", 20, "normal"))
cr.goto(-250, -130)
cr.write("Refresh to play again!", "center", font=("Arial", 20, "normal"))
cr.goto(-250,-150)
cr.color("black")
cr.write("Changes//Version 2.0", "center", font=("Arial", 16, "normal"))
cr.goto(-250,-180)
cr.color("light grey")
cr.write("SECRET GAME HAS A SECRET???", "center", font=("Arial", 16, "normal"))
cr.goto(-250,-210)
cr.write("Timer Added// Bugs need to be fixed", "center", font=("Arial", 16, "normal"))